# Generated by Django 5.2.8 on 2025-11-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sla_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uptimeT', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('uptime30', models.DecimalField(decimal_places=3, max_digits=7)),
                ('uptime90', models.DecimalField(decimal_places=3, max_digits=7)),
                ('uptime90d', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('uptime365', models.DecimalField(decimal_places=3, max_digits=7)),
                ('group', models.CharField(default='NA', max_length=200)),
                ('last_update', models.DateTimeField(verbose_name='date updated')),
            ],
            options={
                'db_table': 'sla_report',
            },
        ),
    ]
